import {
  NO_TRANS_TAG as DEFAULT_NO_TRANS_TAG,
  WORLD_BOOK_DEFAULT_ROLE as DEFAULT_WORLD_BOOK_DEFAULT_ROLE,
} from '../../state/defaults.js';

export const NO_TRANS_TAG = DEFAULT_NO_TRANS_TAG;
export const WORLD_BOOK_SENTINEL_PREFIX = '__STDIFF_WB_G';
export const WORLD_BOOK_DEFAULT_ROLE = DEFAULT_WORLD_BOOK_DEFAULT_ROLE;